gaurun/notification.go
get the Api.PushUri from ConfGaurun
=> output Api.PushUri in the log

gaurun/notification.go
There possibly happens race condition in this line, so use atomic op instead of just adding.
=> Fix race condition

CONFIGURATION.md, gaurun.go
fix https://github.com/mercari/gaurun/issues/14
=> enable to pass port by flags

CONFIGURATION.md, Gomfile, Makefile, cmd/gaurun/gaurun.go, cmd/gaurun_recover/gaurun_recover.go, conf/gaurun.toml, gaurun/apns_http2.go, gaurun/conf.go, gaurun/conf_test.go, gaurun/global.go, gaurun/notification.go, glide.lock, glide.yaml
Removed obsolete code for APNS.
=> experimental: introduced new APNS push notification based HTTP/2 with buford（2nd）

cmd/gaurun_recover/gaurun_recover.go, gaurun/global.go, gaurun/notification.go, glide.lock, glide.yaml
=> gcm: new endpoint.

cmd/gaurun_recover/gaurun_recover.go
=> refactored: used sync.WaitGroup instead of chan.

gaurun/notification.go
=> POST /push: added Content-Length check for the request.

gaurun/apns_http2.go
apns-expiration value is based UTC.
=> apns: fixed invalid Expiration value pass-through.

gaurun/apns_http2.go
As `worker_num` is typically larger than `MaxIdleConnsPerHost` by default, the performance should be improved.
=> APNs: set MaxIdleConnsPerHost as same as core.worker_num.

gaurun/apns_http2.go, glide.lock, glide.yaml
refs: https://github.com/RobotsAndPencils/buford/releases/tag/v0.7.0
=> apns: bumped buford version to v0.7.0.

SPEC.md, cmd/gaurun_recover/gaurun_recover.go, gaurun/apns_http2.go, gaurun/log.go, gaurun/notification.go, samples/client.go
=> apns: Support for content-available inside aps payload

gaurun/notification.go
The current code is a little tricky. refs #26
=> style: simplified sendResponse().

cmd/gaurun_recover/gaurun_recover.go
This problem was appeared in 2e5c805.
=> bugfix: not reached notification with gaurun_recover. refs #37

cmd/gaurun_recover/gaurun_recover.go
=> gaurun_recover: refactored.

SPEC.md, gaurun/conf.go, gaurun/conf_test.go, gaurun/notification.go, gaurun/server.go
API endopoint modification was not useful very well.
=> Abolished API section.

SPEC.md, gaurun/conf.go, gaurun/server.go, gaurun/worker.go
This API modifies core.pusher_max on-the-fly.
=> API: introduced PUT /config/pushers.

.travis.yml, Makefile, README.md
Let's run test automatically. See https://travis-ci.org/mercari/gaurun
=> Add travis setting

SPEC.md, gaurun/apns_http2.go, gaurun/log.go, gaurun/notification.go
this PR resolve https://github.com/mercari/gaurun/issues/53
=> support mutable-content for ios

gaurun/notification.go
**bytes.Buffer** & stream combination is a bit faster than **json.Unmarshal()**.
```go
package main
import (
"testing"
"encoding/json"
"bytes"
)
type ResponseGaurun struct {
Message string `json:"message"`
}
func BenchmarkUnmarshal(b *testing.B) {
msgJson := []byte("{\"message\":\"ok\"}")
for i:=0;i<b.N;i++ {
var res ResponseGaurun
if err := json.Unmarshal(msgJson, &res); err != nil {
b.Fail()
}
}
}
func BenchmarkStream(b *testing.B) {
res := ResponseGaurun{
Message: "ok",
}
for i:=0;i<b.N;i++ {
var buf bytes.Buffer
if err := json.NewEncoder(&buf).Encode(res); err != nil {
b.Fail()
}
}
}
```
```
$ go test -bench . -benchmem
testing: warning: no tests to run
BenchmarkUnmarshal-8     2000000               967 ns/op             272 B/op          4 allocs/op
BenchmarkStream-8        2000000 …
```
=> notification: slightly optimized response generation.

CONFIGURATION.md, gaurun/client_test.go, gaurun/global.go, gaurun/log.go, gaurun/log_test.go, gaurun/notification.go, glide.lock, glide.yaml
=> log: followed latest zap.

gcm/client.go
At first, Sorry for nit pull request.
Rename `Client` method receiver to `c` instead of `s`.
I saw `gcm` package, it's forked from [alexjlockwood/gcm](https://github.com/alexjlockwood/gcm). That's used `Sender` type but now mercari/gaurun uses `Client` type name.
So I think rename to `c` is more readable.
If mercari have own coding policy, please ignore and close it.
Signed CLA.
Thanks.
=> gcm: rename Client method receiver to c

gaurun/global.go
These variables are no longer used.
=> removed unused global variables.

gaurun/notification.go
This functions is no longer used.
=> removed classifyByDevice().

gaurun/global.go
=> style: annotated as comment for global variables.

CONFIGURATION.md, cmd/gaurun/gaurun.go, conf/gaurun.toml, gaurun/conf.go, gaurun/conf_test.go
Add a new config entry, `pid` and support writing a pid file.
=> Support writing pid file

gaurun/stat.go
=> stat: appened charset to Content-Type.

SPEC.md, gaurun/conf.go, gaurun/server.go
This API was not used very well.
=> api: abolished GET /config/app.

gaurun/server_test.go
Add some test code for `gaurun/server.go`
=> test: Add test cases for server.go

gaurun/worker.go, gaurun/worker_test.go
Add some test code for `gaurun/worker.go`
=> test: Add test code for worker

Makefile, gaurun/const.go
* Support APNs payload extensions for `Title & Subtitle` refs #70 Thanks @timakin
* Add UNNotificationCategory option for iOS. refs #73 Thanks @timakin
* Support writing pid file refs #76
* bugfix: set Content-Type: application/json; charset=utf-8 for json response. refs #80
* stat: appened charset to Content-Type. refs #81
* api: abolished GET /config/app. refs #82
=> bumped version to 0.9.0.

gaurun/notification_test.go
=> style: go fmt

Makefile, gaurun/const.go
* support private key with passphrase. refs #98, #99 Thanks @deme0607
* support request tracking by self-inserted ID. refs #95 Thanks @u5surf
=> bumped version to 0.9.1.

SPEC.md
=> Fixed typos and readabilty in SPEC.md

gcm/client.go, gcm/client_test.go, gcm/message.go, gcm/response.go
And fixed link to firebase document.
=> doc: replaced GCM to FCM.

Makefile, gaurun/const.go
* support apns-push-type to the request header for iOS 13+ #122
=> bumped version to 0.11.1

Makefile
=> fix to specify dependencies

buford/README.md
We forked from RobotsAndPencils/buford
=> fix README on buford

Makefile, gaurun/const.go
introduction of major PRs
* update the modules and go version to 1.13 #129
* remove golang.org/x/net/http2 #130
* bug fix #133
=> bumped version to 0.12.0

LICENSE, README.md, gaurun/version.go
=> update copyright year.

CONFIGURATION.md
Please check it on https://github.com/mercari/gaurun/pull/139/files?w=1
=> format markdown file

Makefile, gaurun/const.go
introduction of major PRs
* https://github.com/mercari/gaurun/pull/138
=> dumped version to 0.13.0

SPEC.md, cmd/gaurun_recover/gaurun_recover.go, gaurun/notification.go, gcm/client.go, gcm/message.go, gcm/message_test.go
Please read the CLA carefully before submitting your contribution to Mercari.
Under any circumstances, by submitting your contribution, you are deemed to accept and agree to be bound by the terms and conditions of the CLA.
https://www.mercari.com/cla/
Agreed CLA.
- Added priority parameter
- When I want to be sure to notify push even in deep sleep mode on Android.
- https://firebase.google.com/docs/cloud-messaging/concept-options?hl=en#setting-the-priority-of-a-message
=> Added fcm priority parameter

gaurun/server.go, go.mod, go.sum
lestrrat/go-server-starter has been moved.
=> use lestrrat-go/server-starter instread of lestrrat/go-server-starter

Makefile, gaurun/const.go
* update dependent packages
* add fcm priority parameter #142
=> bumped version to 0.13.1

Makefile, gaurun/const.go
=> bumped version to 0.13.2.

Makefile, gaurun/const.go
- switch package: #155 
- change supported go version: #156
=> chore: bumped version to 0.14.0
