gaurun/notification.go
gaurun/worker.go

Gaurun doesn't retry to push except when server side error is the cause. The result is always same.

enhanced retry mechanism

---

CONFIGURATION.md
conf/gaurun.toml
gaurun/apns_http2.go
gaurun/conf.go
gaurun/conf_test.go
gaurun/global.go
gaurun/notification.go

This parameter controls the timeout for keep-alive connection of HTTP client.
The value is set 30 by default. (It is the default value of the `net/http` client.)

conf: introduced (ios|android).keepalive_timeout.

---

CONFIGURATION.md
conf/gaurun.toml
gaurun/apns_http2.go
gaurun/conf.go
gaurun/conf_test.go
gaurun/notification.go

Previously Gaurun keeped connections to APNs and GCM as same as the number of workers.
But it is not always efficient when the number of workers is large.

conf: introduced keepalive_conns.

---

CONFIGURATION.md
conf/gaurun.toml
gaurun/conf.go
gaurun/conf_test.go
gaurun/stat.go
gaurun/worker.go

In terms of the client, Gaurun pushes asynchronously. But in terms of internal, previously Gaurun's each worker pushed synchronously.
This implementation allows that Gaurun's each worker pushes asynchronously until the number of goroutine for pushing reaches `core.pusher_max`.
If `core.pusher_max` is less than or equal to zero or the number of goroutine for pushing reaches `core.pusher_max`, Gaurun's each worker pushes synchronously.

conf: introduced core.pusher_max for asynchronous pushing.

---

gaurun/apns_http2.go

The behavior is same as before.

apns: not inserted apns-expiration header when Expiry is not given.

---

CONFIGURATION.md
cmd/gaurun/gaurun.go
gaurun/conf.go
gaurun/conf_test.go
gaurun/notification.go
gaurun/worker.go

These parameters will be dynamic values by API. Therefore what atomic.(Store|Load)IntXX is available is required.

core: changed type for core parameters.

---

gaurun/stat.go
gaurun/worker.go

Previously `pusherCount` and `pusher_max` were the shared value between workers. Workers tend to be blocked because `pusherCount` reaches `pusher_max` quickly.
This implementation makes `pusherCount` independent by each worker and gives `pusher_max` to each worker.

optimize: mitigated the blocking between workers.

---

cmd/gaurun/gaurun.go
cmd/gaurun_recover/gaurun_recover.go
gaurun/conf.go
gaurun/global.go
gaurun/log.go
gaurun/log_test.go
gaurun/notification.go
gaurun/worker.go
glide.lock
glide.yaml

use github.com/uber-go/zap instead of github.com/Sirupsen/logrus for access/error logs. This breaks compatibility about log format and achieves fully json logging.
zap is very complex to use (ex: omitempty), but slightly faster than other loggers. This is a benchmark before/after this changes for `gaurun.LogPush`.
**before**
```
go test github.com/mercari/gaurun/gaurun -benchmem -benchtime 5s -bench .   
BenchmarkLogPushIOSOmitempty-4   	  500000	     12257 ns/op	    1816 B/op	      18 allocs/op
BenchmarkLogPushIOSFull-4        	  500000	     13893 ns/op	    2008 B/op	      18 allocs/op
```
**after**
```
go test github.com/mercari/gaurun/gaurun -benchmem -benchtime 5s -bench .     
BenchmarkLogPushIOSOmitempty-4   	 1000000	      6060 ns/op	     945 B/op	       4 allocs/op …
```

use zap instead of logrus

---

glide.lock
glide.yaml

refs: https://github.com/RobotsAndPencils/buford/releases/tag/v0.12.0

glide: bumped buford version to 0.12.0.

---

CONFIGURATION.md
README.md
gaurun/apns_http2.go
gaurun/client.go
gaurun/client_test.go
gaurun/conf.go
gaurun/conf_test.go
gaurun/notification.go

`http.Transport.IdleConnTimeout` was introduced in Go1.7.
This value is used as an expiration time for an idling connection.
And fixed mistaken handling bug of `(ios|android).keepalive_timeout` previously.

APNs, GCM: introduced http.Transport.IdleConnTimeout from Go1.7.

---

cmd/gaurun/gaurun.go
gaurun/log.go
glide.lock
glide.yaml

by using [github.com/client9/reopen](https://github.com/client9/reopen)

reopen access/error logs on sighup

---

.travis.yml
CONFIGURATION.md
README.md
cmd/gaurun/gaurun.go
conf/gaurun.toml
gaurun/conf.go
gaurun/server.go
gaurun/worker.go
glide.lock
glide.yaml

For hot deploy, support `lestrrat/go-server-starter`. Graceful shutdown is done by Go1.8 new feature. 
Graceful shutdown is kicked by `server-starter` by sending `SIGTERM`. If it receives `SIGTERM`, first it shutdown `net/http` server. After shutdown, then it will wait until queue will be empty. 
Tests are done by same way as [this](https://github.com/mercari/widebullet/pull/10) but using `samples/client.go`.  
Not yet done queue flushing test ... (any suggestion how to do this ?)

Support graceful shutdown and hot-deploying

---

gaurun/stat.go

Not wrapped **[]bytes** by **string()**.

stat: minor optimized.

---

cmd/gaurun/gaurun.go
gaurun/client.go
gaurun/client_test.go
gaurun/const.go
gaurun/log.go
gaurun/notification.go

Previously, gaurun could not start without ssl certificate and key for APNs even if target application is only Android.

Enabled startup without ssl certificate and key for APNs.

---

cmd/gaurun/gaurun.go

The error message `failed to init http client` is difficult to understand what's going on.

Include err of init http client to log

---

SPEC.md
cmd/gaurun_recover/gaurun_recover.go
gaurun/apns_http2.go
gaurun/log.go
gaurun/notification.go
samples/client.go

This PR allows to send `Title` and `Subtitle` with an existing payload.
From iOS ver10, it supports Bold-styled title and subtitles to display rich notifications.

Support APNs payload extensions for `Title & Subtitle`

---

SPEC.md
cmd/gaurun_recover/gaurun_recover.go
gaurun/apns_http2.go
gaurun/log.go
gaurun/notification.go
samples/client.go

This commit will enable `unnotificationcategory` for iOS.
https://developer.apple.com/documentation/usernotifications/unnotificationcategory
It'll categorize notifications if a user chose not to display preview of notifications on setting.
And it'll also let you to handle actions that depends on categories.

Add UNNotificationCategory option for iOS. 

---

gaurun/notification.go

Previously, Gaurun returned response with the header of `Content-Type: text/plain` even if response body is json. 
This was caused by the execution order of `http.ResponseWriter` functions. `w.Header().Set(key, val)` must be called before `WriteHeader(code)`. Otherwise, response header is not set.

bugfix: set Content-Type: application/json; charset=utf-8 for json response.

---

SPEC.md
gaurun/log.go
gaurun/notification.go
gaurun/notification_test.go

Sometimes we cannot send the notification to iOS/Android clients. For example, when the notification is expired.
I want to get the correspondence between the requests to Gaurun and the logs recorded by Gaurun. It helps us to investigate the reason why the notification was not delivered to the client.
* Add `TrackingID` parameter to `gaurun.RequestGaurunNotification`
* Enable `gaurun.LogPush` to store the `TrackingID` when it is given
* We can give `tracking_id` to `notification` parameter for Gaurun `/push` request
* We can see `tracking_id` in the push log stored by Gaurun

Add parameter for tracking each request in the log

---

CONFIGURATION.md
gaurun/client.go
gaurun/conf.go
gaurun/conf_test.go

refs #93
Please read the CLA carefully before submitting your contribution to Mercari.
Under any circumstances, by submitting your contribution, you are deemed to accept and agree to be bound by the terms and conditions of the CLA.
https://www.mercari.com/cla/

change the default value of use_fcm to true

---

cmd/gaurun_recover/gaurun_recover.go
gaurun/notification.go

Failure is changed only when using `Send`.

bug: Failure is not changed when using SendNoRetry

---

cmd/gaurun/gaurun.go

Error string should not be capitalized or end with punctuation.

fix error strings format

---

Makefile
gaurun/const.go

* android: abolished GCM support.

bumped version to 0.11.0.

---

SPEC.md
conf/gaurun.toml
gaurun/conf.go
gaurun/conf_test.go
gaurun/notification.go
gaurun/notification_test.go

I'd like to send push notification with empty message.
Apple and FCM don't say that message body is required.
use case:
I'd like to update badge count on iOS by sending push notifications without showing any alert to users.
To do this, I should send push notifications with empty body.
Apple's document:
https://developer.apple.com/library/archive/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/PayloadKeyReference.html#//apple_ref/doc/uid/TP40008194-CH17-SW5
FCM' document:
https://firebase.google.com/docs/cloud-messaging/http-server-ref#notification-payload-support

Allow empty message

---

gaurun/notification.go

staticcheck says
```
gaurun/notification.go:229:3: this value of err is never used (SA4006)
```
It is a bug. I fixed it.

fix to check error

---

cmd/gaurun/gaurun.go

if signal channel is close, it causes infinite loop.
Now, it is not close but I fixed it

fix infinite loop if channel is close

---

README.md

This term does not reflect current state. (And they are involved in commit log.)

doc: removed commiters in README.md.

---

buford/token/token.go
go.mod
go.sum

switch to a fork of jwt-go with a fix to CVE-2020-26160

---

.github/workflows/go.yml
README.md

chore: update support go version

---

buford/token/token.go
go.mod
go.sum

SSIA
- we switched to fork in https://github.com/mercari/gaurun/pull/150 because of security.
- jwt library is now maintained in https://github.com/golang-jwt/jwt

feat: switch from fetched-oss/jwt-go to golang-jwt/jwt
